### ISSUE TITLE
For multiple plate sampler blocks "select primer" only appears for the first block

### ISSUE THREAD

**Issue by kathryn-explorable** [lab-grid/flow#116]
I think the solution here is to just remove the "Select primer" dropdown entirely. It isn't used in the barcode mapping at all. And if someone did want to add a primer selector element, they could do that with the "text question" or "options" block.

This issue doesn't currently break the UI, however it is confusing to users who think they should use the "select primer" dropdown, but they can't, and it doesn't do anything.

**Comment by robotoer** [comment]
I think this might be because the select primer only shows up if there are primers defined for the step in the protocol

**Comment by kathryn-explorable** [comment]
You are correct! There was an empty string primer there that was causing this dropdown to show up. 
I was able to delete it from the protocol. Closing!
