### ISSUE TITLE
create demo protocol

### ISSUE THREAD

**Issue by kathryn-explorable** [lab-grid/flow#123]
At flow.aws.labgrid.com
For new users to see what is possible with the app

**Comment by kathryn-explorable** [comment]
A demo protocol does exist now, in my workspace. 

Also it would be nice to share this protocol with user "*"; @robotoer can you think of a way to do that?

@robotoer when I "save" the demo protocol, it gives this strange error (see screenshot). Even stranger, the "save" DOES work. So I'm just ignoring the error!

<img width="845" alt="Screen Shot 2021-04-07 at 4 13 19 PM" src="https://user-images.githubusercontent.com/59711202/113946090-8111b800-97bc-11eb-971d-e8d2a81dce72.png">

**Comment by robotoer** [comment]
Hmm, wasn't able to reproduce this, but I am adding support for subject rules with wildcards.

**Comment by robotoer** [comment]
I can try again with your protocol once the wildcard permissions are added.
