### ISSUE TITLE
"Review and sign off" flow

### ISSUE THREAD

**Issue by kathryn-explorable** [lab-grid/flow#15]
A run or a protocol should be able to be "signed" (and optionally, "witnessed" or "reviewed and signed" by a second person). A "signed" run or protocol can't be edited. (Unless it is later "unsigned" and then edited...) For each user who "signs", it needs to record the user's name and the date/time of signing, and then change status to "signed".

**Comment by kathryn-explorable** [comment]
Probably you are aware of this, but just FYI in case not. Currently, the run object is saved, but the data in the run is not saved. Like, I type things in boxes and then they are gone...
Clicking "sign" does not actually change the status from todo to "signed".

**Comment by robotoer** [comment]
Thanks for testing! You are correct that this is likely broken right now.

**Comment by robotoer** [comment]
Some notes for myself: See if this can be done with `casbinmodel.conf`
