### ISSUE TITLE
Deploy a live labflow instance

### ISSUE THREAD

**Issue by kathryn-explorable** [lab-grid/flow#2]
TBD, Kubernetes?

**Comment by kathryn-explorable** [comment]
I created a new GCP project and just added you to it, you should have just received an email.
Also fine if you don't want to use it!

**Comment by robotoer** [comment]
Thanks! I got in successfully. Will have something deployed today or
tomorrow

**Comment by robotoer** [comment]
Upon further consideration, I ended up going with a simple terraform deployed google cloud run stack for now. It probably is best to wait on the kubernetes-ification until we're ready to deploy this for a customer.

**Comment by kathryn-explorable** [comment]
Just tested flow.labgrid.com, and when I saw it wasn't working I went to Auth0 to try to allow requests from that URL... So FYI that's why that new url is added to the "Web" application there under origins/callback/logout. But I failed to get it working. I tried to add a new API at api.flow.labgrid.com, it wouldn't let me, and I decided I should stop guessing!

**Comment by robotoer** [comment]
Hey Kathryn,

The application was broken due to some bash scripting duct tape that I put
in place to inject environment variables into the webapp on container start
instead of at container build. It should be fixed now!

Robert
