### ISSUE TITLE
Additional user role(s)

### ISSUE THREAD

**Issue by robotoer** [lab-grid/flow#34]
There should be at least 1 restricted user type, who can run protocols but can't edit protocols. Open to naming ideas for these admin/not user roles... "admin" and "operator"?

- [ ] Add an administrators policy editor UI

**Comment by kathryn-explorable** [comment]
This was completed when we added the casbin library. Examples are included for roles "admin" and "user" (user can run protocols but cannot edit protocols). Arbitrary permissions groups can also be created using this library.
