### ISSUE TITLE
Add in-app barcode reader support

### ISSUE THREAD

**Issue by kathryn-explorable** [lab-grid/flow#6]
This may necessitate moving to react-native fully.

**Comment by kathryn-explorable** [comment]
@robotoer I was researching how to just make the web app read from a handheld barcode scanner. It sounds like it just acts like a keyboard so it shouldn't be hard. [Here](https://stackoverflow.com/questions/42325613/how-to-use-barcode-scanner-in-web-application) are some Javascript examples. 

I think this barcode scanner will require installing a driver on the computer that it's plugged into. So I still like the react native idea as a longer term solution that requires less setup. But I'm guessing that will require some tweaking to get accurate reading of linear barcodes, so in the short term is seems safer to rely on the barcode scanner that comes with the barcode label printer.

**Comment by robotoer** [comment]
Thanks for doing that research! As far as I can tell, it shouldn't be too hard to get both working.

Regarding tweaking necessary to get the react native app version working, could you try out the test native app that's already in the project on some real labels once you have the printer in hand? My guess is that it should be able to read numbers from linear barcodes as-is!

**Comment by robotoer** [comment]
I'll get started on the javascript reader this weekend!

**Comment by kathryn-explorable** [comment]
Cool thanks! The other barcode-related thing (your call if it should be a separate ticket), is the ability to query other runs, by barcode. There is a 384-well plate barcode scan in pretty much every protocol, and later protocols need to grab info from earlier protocols to know what's in that plate, even if the earlier run was completed by a different person...

**Comment by robotoer** [comment]
So upon further research it seems that the way these desktop barcode scanners seem to work is that upon scanning a barcode successfully, they "enter" the barcode's id/number/contents by simulating keypresses that match the id/number/contents. Thus, as long as the user has focused (read: clicked on) the input they want to scan a barcode label into, then it should just work as is.

**Comment by robotoer** [comment]
Regarding the other data lookup UI, gotcha. Should be coming this week!

**Comment by kathryn-explorable** [comment]
Marking this done since it works with a handheld barcode scanner.
