### ISSUE TITLE
Upload plate mappings block should allow space in barcodes

### ISSUE THREAD

**Issue by kathryn-explorable** [lab-grid/flow#69]
I received another example barcodes file, where they tried to make the format what we expect (plate, well, sample), but it has a space before each barcode, just because their barcode reader adds that. This breaks our barcode reader! Full example in our GDrive folder, and short example here:

 3000526945,A1, 5000566137
 3000526945,A2, 5000566138
 3000526945,A3, 5000566139
 3000526945,A4, 5000566140

**Comment by kathryn-explorable** [comment]
The error is in this line of RunBlockEditor.tsx
const [, rowRaw, columnRaw] = cell.match(cellRegex);

**Comment by robotoer** [comment]
Should be fixed as of [aaa02565](https://github.com/lab-grid/flow/commit/aaa02565676382d371e2d688f6a51abfe994a8db)
