### ISSUE TITLE
Show signature when user hits "sign" button

### ISSUE THREAD

**Issue by kathryn-explorable** [lab-grid/flow#75]
Let's grab "Full name" from user's profile and fill in the signature box when they hit "sign".

**Comment by robotoer** [comment]
This should already be implemented. Let me know if that's something that doesn't work for you. I tested this on https://flow.labgrid.com/ with success in both protocols/runs.

**Comment by kathryn-explorable** [comment]
You're right it does work! It refreshes the page and pops me to the top of the page, which is a little disorienting, but not a huge deal.

**Comment by kathryn-explorable** [comment]
Closing since this works.
