### ISSUE TITLE
2x2 grid pic next each "plate sampler" input plate

### ISSUE THREAD

**Issue by kathryn-explorable** [lab-grid/flow#90]
For the 96->384 transfer, we should show a pic next to each "input plate #"

I think 2x2 grid that is shaded in one quadrant, indicating which of the four 384-well plate quadrants that input plate is going into. And, let's make each of the 4 images a different color... I will attach pics here that correspond to actual sticker colors.

**Comment by kathryn-explorable** [comment]
![fourth_quadrant](https://user-images.githubusercontent.com/59711202/103982583-9bde7d00-5138-11eb-9163-e6683fe59388.png)
![third_quadrant](https://user-images.githubusercontent.com/59711202/103982585-9c771380-5138-11eb-9513-8b2dd2cee897.png)
![second_quadrant](https://user-images.githubusercontent.com/59711202/103982586-9c771380-5138-11eb-86c0-259f1760a427.png)
![first_quadrant](https://user-images.githubusercontent.com/59711202/103982587-9d0faa00-5138-11eb-910e-7052ea35bf01.png)

Here are the quadrant pics for the plate sampler block... I'm going to make a small attempt to put these in place, but my css skills are not great so we'll see how it goes!

**Comment by kathryn-explorable** [comment]
Ok I failed to do this tonight, because I couldn't run the app locally. (It looked like postgres was running but I couldn't connect to it.) But the idea here is that these pics are really tiny, and go in-row with each of the 4 plate sampler inputs.

The goal here is to visually guide the techs. The 4 plates they are pipetting have these 4 colors of stickers on them.

**Comment by robotoer** [comment]
Ah, I can try my hand at that once the AWS stack is deployed.

Regarding the local environment issues, I would suggest making note of
which password was used (set in .env) to create your local .postgres/
directory (in the root of the project). If you swap the db password to
connect to the octant db for example, you'll need to change the password
back to the one that corresponds to your local postgres database. Also try
adding the environment variable: POSTGRES_HOSTNAME=localhost


Robert

**Comment by kathryn-explorable** [comment]
I filed a PR for this one, so I'm closing the issue.
The team might have suggested improvements for the pics (e.g. green is lower right!) but if so I will file a new issue.
