### ISSUE TITLE
Create a block for adding reagent NOT to a plate

### ISSUE THREAD

**Issue by kathryn-explorable** [lab-grid/flow#97]
i.e. same as existing add reagents block but without the plate field.

This block is for creating a bulk reagent to be used in other protocol steps.

**Comment by kathryn-explorable** [comment]
Adding you Robert, in case you are able to get to this sooner than me. 

Basically we need a more generic block, for just adding a reagent. But the formula needs to be available, so that's why this is more than just a checkbox.

**Comment by robotoer** [comment]
This should be deployed!

**Comment by kathryn-explorable** [comment]
Tested! It "works" but there is 1 major issue: the variables are restricted to be integers (measurements need to be floats).

Also, in the protocol editor, it says "Error: unrecognized block type: add-reagent" for this new block. However, since this only visible to protocol editors, this is not as important to fix.
