### ISSUE TITLE
Allow signature block without "witness"

### ISSUE THREAD

**Issue by kathryn-explorable** [lab-grid/flow#99]
Turns out witness is not necessary

**Comment by kathryn-explorable** [comment]
I don't know whether this should be solved as a nice "option" for each section, to turn on or off the second signature... Or if we just need to comment out this code right now, but for our immediate needs, the 2nd signatures has been deemed overkill, and therefore a waste of time for the team.

**Comment by robotoer** [comment]
Make sure that "completed" status works properly (happens when signed, if no witness is needed for section)
